CREATE TABLE IF NOT EXISTS `socials` (
`id` 			BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
`code`	 		VARCHAR(255) NULL DEFAULT NULL,
`social` 		VARCHAR(50) NOT NULL,
`user_id` 		INT(10) UNSIGNED NOT NULL,
`status` 		ENUM('enable','expire','disable') NOT NULL DEFAULT 'enable',
`email`	 		VARCHAR(255) NULL DEFAULT NULL,
`verified` 		bit(1) NULL DEFAULT NULL,
`name`	 		VARCHAR(255) NULL DEFAULT NULL,
`family` 		VARCHAR(255) NULL DEFAULT NULL,
`displayname`	VARCHAR(500) NULL DEFAULT NULL,
`gender` 		VARCHAR(255) NULL DEFAULT NULL,
`language` 		VARCHAR(50) NULL DEFAULT NULL,
`picture` 		VARCHAR(1000) NULL DEFAULT NULL,
`hd`			VARCHAR(500) NULL DEFAULT NULL,
`link`			VARCHAR(1000) NULL DEFAULT NULL,
`desc`			text NULL DEFAULT NULL,
`meta`			mediumtext NULL DEFAULT NULL,
`createdate` 	DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
`date_modified` TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,
PRIMARY KEY (`id`),
CONSTRAINT `sessions_user_id` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `users` ADD  `user_two_step` bit(1)  NULL DEFAULT NULL;
