ALTER TABLE `users` ADD `user_username` VARCHAR(100) CHARACTER SET utf8mb4 NULL DEFAULT NULL;
ALTER TABLE `users` ADD `user_group` VARCHAR(100) CHARACTER SET utf8mb4 NULL DEFAULT NULL;
ALTER TABLE `users` ADD `user_file_id` int(20) UNSIGNED NULL DEFAULT NULL;
ALTER TABLE `users` ADD `user_chat_id` int(20) UNSIGNED NULL DEFAULT NULL;
